version: '3.8'

services:
  db:
    image: postgres:13.0-alpine

    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:6.2-alpine

    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass mypass
    volumes:
      - cache:/data

  celery:
    build: ../diplom
    env_file:
      - ./.env
    command: celery -A diplom worker -l INFO
    depends_on:
      - redis

  flower:
    image: mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://:mypass@redis:6379/0', '--port=5555' ]
    ports:
      - 5557:5555
    depends_on:
      - redis

  web:
    build: ../diplom
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    command: >
      bash -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0:8000 diplom.wsgi"

  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

      - static_value:/var/html/static/

      - media_value:/var/html/media/

    depends_on:
      - web

volumes:
  static_value:
  media_value:
  cache:
    driver: local
