# Generated by Django 4.2.1 on 2023-06-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_geo_lat_alter_event_geo_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='geo_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='geo_lon',
            field=models.FloatField(null=True),
        ),
    ]
