# Generated by Django 4.2.1 on 2023-06-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_options_event_description_event_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
