# Generated by Django 4.2.1 on 2023-05-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_favouritenews'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favouritenews',
            constraint=models.UniqueConstraint(fields=('user', 'new'), name='favourite news unique validator'),
        ),
    ]
