# Generated by Django 4.2.1 on 2023-05-12 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_favouritenews_favourite_news_unique_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(null=True, upload_to='news/images/'),
        ),
    ]
